// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: AAAA.proto

package XXXX

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AAAAClient is the client API for AAAA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AAAAClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type aAAAClient struct {
	cc grpc.ClientConnInterface
}

func NewAAAAClient(cc grpc.ClientConnInterface) AAAAClient {
	return &aAAAClient{cc}
}

func (c *aAAAClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/xxxx.XXXX.AAAA/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AAAAServer is the server API for AAAA service.
// All implementations must embed UnimplementedAAAAServer
// for forward compatibility
type AAAAServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedAAAAServer()
}

// UnimplementedAAAAServer must be embedded to have forward compatible implementations.
type UnimplementedAAAAServer struct {
}

func (UnimplementedAAAAServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAAAAServer) mustEmbedUnimplementedAAAAServer() {}

// UnsafeAAAAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AAAAServer will
// result in compilation errors.
type UnsafeAAAAServer interface {
	mustEmbedUnimplementedAAAAServer()
}

func RegisterAAAAServer(s grpc.ServiceRegistrar, srv AAAAServer) {
	s.RegisterService(&AAAA_ServiceDesc, srv)
}

func _AAAA_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AAAAServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xxxx.XXXX.AAAA/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AAAAServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AAAA_ServiceDesc is the grpc.ServiceDesc for AAAA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AAAA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xxxx.XXXX.AAAA",
	HandlerType: (*AAAAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _AAAA_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AAAA.proto",
}
